name: dart_mapper_generator
description: The dart mapper generator, useful to autogenerate mapping code.
version: 0.8.0
repository: https://github.com/MyLittleSuite/dart_mapper.git
issue_tracker: https://github.com/MyLittleSuite/dart_mapper/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  analyzer: 9.0.0
  build: ^4.0.0
  code_builder: ^4.10.1
  dart_style: ^3.0.0
  dart_mapper: ^0.8.0
  source_gen: ^4.0.0
  strings: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.8
  lints: ^6.0.0
  source_gen_test: ^1.0.6
  test: ^1.25.1
